services:
  washing-api:
    image: washing-api
    container_name: washconnect-backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=WashingDB;User Id=sa;Password=Your_Strong_Password123!;TrustServerCertificate=True;
    depends_on:
      - sqlserver

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: washconnect-db
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Your_Strong_Password123!
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - sqlvolume:/var/opt/mssql

volumes:
  sqlvolume: